# Generated by Django 3.2.13 on 2022-04-23 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_banner_image_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='image_url',
            field=models.ImageField(max_length=255, upload_to='banner', verbose_name='广告图片'),
        ),
    ]
