# Generated by Django 3.2.9 on 2022-04-28 17:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='courselesson',
            name='lesson',
        ),
    ]
