# Generated by Django 3.2.9 on 2022-04-29 20:59

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0003_courselesson_lesson'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='brief',
            field=ckeditor.fields.RichTextField(blank=True, max_length=2048, null=True, verbose_name='详情介绍'),
        ),
    ]
