# Generated by Django 3.2.9 on 2022-04-29 21:18

from django.db import migrations
import mdeditor.fields


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0006_alter_course_brief'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='brief',
            field=mdeditor.fields.MDTextField(blank=True, null=True, verbose_name='详情介绍'),
        ),
    ]
