# Generated by Django 3.2.13 on 2022-05-02 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='pay_type',
            field=models.SmallIntegerField(choices=[(0, '支付宝'), (1, '微信支付')], default=1, verbose_name='支付方式'),
        ),
    ]
